apiVersion: v1
kind: Service
metadata:
  name: nodeport-web-app
spec:
  type: NodePort
  selector:
    app: web-app-pod
  ports:
  #-- port du service cluster IP
  - port: 1000
  #-- port du conteneur
    targetPort: 80
    protocol: TCP
  #--- Port d'un service node port entre 30000 et 32767
    nodePort: 30001
    name: http-port
  
