apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  #la definition du pod
  template:    
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
        prod: nginx-prod
    spec:
      containers:
        - name: container-nginx
          image: nginx:perl
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"