apiVersion: v1
kind: Service
metadata:
  name: clusterip-http-service
spec:
  type: ClusterIP
  selector:
    app: nginx-pod
  ports:
  #-- port du service
  - port: 1000
  #-- port du conteneur
    targetPort: 80
    name: http-port
