apiVersion: v1
kind: ResourceQuota
metadata:
  name: limit-env-dev
  namespace: env-dev
spec:
  hard:
    pods: "2"
    services: "3"
    limits.cpu: "1"
    limits.memory: 1Gi
    requests.cpu: "500m"
    requests.memory: 500Mi