apiVersion: v1
kind: Pod
metadata:
  name: debian-pod
  labels:
    app: debian-pod
spec:
  serviceAccount: first-account
  serviceAccountName: first-account
  containers:
    - name: container-debian
      image: redis
      imagePullPolicy: IfNotPresent