apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: first-role
  labels:
    name: first-role
rules:
  - resources:
      - pods
      - services
    verbs:
      - get
      - list
      - create
      - delete
    apiGroups:
      - "v1"
      - "apps/v1"
 
