apiVersion: v1
kind: ServiceAccount
metadata:
  name: first-account
  labels:
    app: api-rest

# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: first-role
#   labels:
#     name: first-role
# rules:
#   - resources:
#       - pods
#       - services
#     verbs:
#       - get
#       - list
#       - create
#       - delete
#     apiGroups:
#       - "v1"
#       - "apps/v1"
 
# ---

# apiVersion: rbac.authorization.k8s.io/v1 
# kind: ClusterRoleBinding
# metadata:
#   name: first-cluster-role-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: first-role
# subjects:
#   - kind: ServiceAccount
#     name: first-account
#     namespace: default
