apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis-pod
spec:
  containers:
    - name: container-redis
      image: redis
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "100m"
          memory: "100Mi"