apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: exercice-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  #la definition du pod
  template:    
    metadata:
      name: web-app
      labels:
        app: web-app
    spec:
      containers:
        - name: container-nginx
          image: nginx
          imagePullPolicy: IfNotPresent
        - name: container-mysql
          image: mysql