apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  #la definition du pod
  template:    
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: container-nginx
          image: nginx
          imagePullPolicy: IfNotPresent